CFD Simulations using the Jupyter Notebooks v1.0
DesignSafe-CI/DS_Use_Case_template pull request #11
Opened 2022-03-11 22:28 UTC by moontrip

2022-03-15 00:51 UTC, meshl5555 approved these changes

2022-04-06 21:39 UTC, kks32 commented on docs/kareen/usecase.md
> +The Jupyter Notebooks have been widely used in science and engineering communities as an open-source interactive literate programming paradigm. It has the capabilities of combining text, images or vi
Could you please remove the Jupyter background info and talk about how to use Jupyter with OpenFOAM.

2022-04-06 21:40 UTC, kks32 commented on docs/kareen/usecase.md
> -* This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).
We need the license info

2022-04-06 21:40 UTC, kks32 commented on docs/kareen/usecase.md
> -* This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).
* This software is distributed under the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.html).

2022-04-06 21:40 UTC, kks32 commented on docs/kareen/usecase.md
> +<br/>
```suggestion

```

2022-04-06 21:41 UTC, kks32 commented on docs/kareen/usecase.md
> -* Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.
* Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.

2022-04-06 21:50 UTC, kks32 requested changes
The current usecase reads more like a paper and describes the motivation behind the use of Jupyter. We would like the usecase to be a demonstration / an example of how to use your code for others to reuse. 

We really like fig 1. Following on Fig 1, if you could write a section on Geometry, Mesh, Case Setup - Solver and Post processing.

2022-04-06 21:50 UTC, kks32 commented on docs/kareen/usecase.md
> +* Please cite Ding and Kareem (2021) to acknowledge the use of any resources from this use case.<br>
```suggestion
* Please cite Ding and Kareem (2021) to acknowledge the use of any resources from this use case.
```

2022-04-06 21:50 UTC, kks32 commented on docs/kareen/usecase.md
> +Ding, F., and Kareem, A. (2021). Using the Jupyter Notebooks as a tool for CFD simulations, 6th American Association for Wind Engineering (AAWE) Workshop (online),
```suggestion
* Ding, F., and Kareem, A. (2021). Using the Jupyter Notebooks as a tool for CFD simulations, 6th American Association for Wind Engineering (AAWE) Workshop (online),
```

2022-04-06 21:50 UTC, kks32 commented on docs/kareen/usecase.md
> +<br/>
Please remove this section as it doesn't help explain the usecase itself.

2022-04-15 19:05 UTC, moontrip commented
@erathje71 @kks32 We have revised our use case document following your suggestions and comments in this PR. We think that this is much improved from the last doc owing to your advices and we thank for your great efforts to enhance the quality of our use case.

Please feel free to leave comments in this PR if further changes are needed. Happy Easter!

2022-04-19 16:13 UTC, kks32 approved these changes

2022-04-19 16:14 UTC, merged