Modeling Reinforced Concrete Walls with Shell Elements to Simulate Through Opensees and Using Jupyter to Post Process Results
DesignSafe-CI/DS_Use_Case_template pull request #13
Opened 2022-03-15 17:18 UTC by stokljos

Testing

2022-04-04 18:59 UTC, kks32 requested changes
Please make suggested changes

2022-04-04 18:59 UTC, kks32 commented on docs/lowes/usecase.md
> +<!--- this is a comment --->
```suggestion
```

2022-04-04 18:59 UTC, kks32 commented on docs/lowes/usecase.md
>  * This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).
```suggestion
* This software is distributed under the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.html).  
```

2022-04-04 18:59 UTC, kks32 commented on docs/lowes/usecase.md
> +<img src="img/ShellEle.JPG" width="500" height="250" />
```suggestion
<img src="../img/ShellEle.JPG" width="500" height="250" />
```

2022-04-04 18:59 UTC, kks32 commented on docs/lowes/usecase.md
> +* Section 1: Initializion of the model.
```suggestion

* Section 1: Initializion of the model.  
```

2022-04-04 18:59 UTC, kks32 commented on docs/lowes/usecase.md
> +   * The crushing energy and fracture energy are calculated and wrote to the .tcl file. The equations for these values come from (Nasser et al.)  Below is the code:
```suggestion
   * The crushing energy and fracture energy are calculated and wrote to the .tcl file. The equations for these values come from (Nasser et al.)  Below is the code:
   
```

2022-04-04 18:59 UTC, kks32 commented on docs/lowes/usecase.md
> +The sections of the modeling script are: [Modeling Script](https://jupyter.designsafe-ci.org/user/stokljos/notebooks/MyData/UseCaseScripts/TCL_Script_Creator.ipynb)
This script is not in Community Data and cannot be viewed by others. Please update the link.

2022-04-04 18:59 UTC, kks32 commented on docs/lowes/usecase.md
> +### Load-Displacment Graph
```suggestion
### Load-Displacement Graph
```

2022-04-19 16:17 UTC, kks32 requested changes
I cannot access the Jupyter Notebooks, please make them available in the community data so I can merge.

2022-04-19 17:03 UTC, stokljos commented
I will update that soon and let you know when it is done!

On Tue, Apr 19, 2022, 9:17 AM Krishna Kumar ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I cannot access the Jupyter Notebooks, please make them available in the
> community data so I can merge.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/13#pullrequestreview-945975786>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOGTV27B6KQXJDCUYVMKLSTVF3MB3ANCNFSM5QZLTXXQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-19 18:27 UTC, stokljos commented
The links are updated. Let me know if there's anything else I can do for
you.

On Tue, Apr 19, 2022, 10:02 AM Josh Stokley ***@***.***> wrote:

> I will update that soon and let you know when it is done!
>
> On Tue, Apr 19, 2022, 9:17 AM Krishna Kumar ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> I cannot access the Jupyter Notebooks, please make them available in the
>> community data so I can merge.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/13#pullrequestreview-945975786>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AOGTV27B6KQXJDCUYVMKLSTVF3MB3ANCNFSM5QZLTXXQ>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-04-19 19:04 UTC, kks32 approved these changes

2022-04-19 19:04 UTC, merged