Merging arduino use-case version1
DesignSafe-CI/DS_Use_Case_template pull request #18
Opened 2022-03-16 06:49 UTC by parduino

Version 1 of arduino use-case material

2022-03-24 21:30 UTC, kks32 commented on docs/arduino/usecase.md
> +[//]: <![Propagation of vertical waves in site response analysis](img/SRschematic2.PNG){width=50%}>
```suggestion
```

2022-04-04 18:50 UTC, kks32 requested changes
Could you please update the doc with the suggested changes. Thanks
!

2022-04-04 18:50 UTC, kks32 commented on docs/arduino/usecase.md
>  * This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).
```suggestion
* This software is distributed under the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.html).  
```

2022-04-04 18:50 UTC, kks32 commented on docs/arduino/usecase.md
> +<img src="img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>
```suggestion
<img src="../img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>
```

2022-04-04 18:50 UTC, kks32 commented on docs/arduino/usecase.md
>  ### Description
```suggestion
## Description 
```

2022-04-04 18:50 UTC, kks32 commented on docs/arduino/usecase.md
>  ### Description
Please use second level H2 so they appear on the sidebar

2022-04-04 18:50 UTC, kks32 commented on docs/arduino/usecase.md
> +<img src="img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>
Image url is one level up

2022-04-04 18:50 UTC, kks32 commented on docs/arduino/usecase.md
>  **Authors, Affiliations**
```suggestion
```

2022-04-05 01:08 UTC, parduino commented
Made suggested modifications

2022-04-16 19:21 UTC, parduino commented
Hi Krishna,

  Silly question on use case document.
Why do you suggest to use


<img src="../img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>


If the img/ folder is in the same location as the usecase.md file… ??
Or are you planning to have a different location for the img folders??
I would use

<img src="img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>

I may be missing something here.. ☺

Pedro

From: Krishna Kumar ***@***.***>
Sent: Monday, April 4, 2022 11:51 AM
To: DesignSafe-CI/DS_Use_Case_template ***@***.***>
Cc: Pedro Arduino ***@***.***>; Author ***@***.***>
Subject: Re: [DesignSafe-CI/DS_Use_Case_template] Merging arduino use-case version1 (PR #18)


@kks32 requested changes on this pull request.

Could you please update the doc with the suggested changes. Thanks
!

________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842040552>:

>



 ## Background







 ### Citation and Licensing







-* Please cite [AUTHORS et al. (20xx) - example of published project](https://doi.org/10.17603/ds2-3zdj-493) to acknowledge the use of any resources from this use case.



+* Please cite [Arduino, P. et al. (2022)](https://doi.org/10.17603/ds2-3zdj-493) to acknowledge the use of any resources from this use case.







 * Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.







 * This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).


⬇️ Suggested change

-* This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).



+* This software is distributed under the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.html).



________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842042641>:

>



 * Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.







 * This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).







 ### Description







-Enim ut sem viverra aliquet.  Nisi scelerisque eu ultrices vitae auctor. Scelerisque viverra mauris in aliquam.  Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Sed adipiscing diam donec adipiscing tristique.  In pellentesque massa placerat duis. Tortor condimentum lacinia quis vel eros donec ac. Sed velit dignissim sodales ut eu sem. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Quis risus sed vulputate odio ut.



+Site response analysis for liquefiable soils is fundamental in the estimation of demands on civil infrastructure including buildings and lifelines. Current state of the art in numerical methods in geotechnical engineering require the use of advance constitutive models and fully couple nonlinear finite element (FEM) tools. Advanced constitutive models require calibration of material parameters based on experimental tests. These parameters include uncertainties that in turn propagate to uncertenties in the estimation of demands. The products included in this use-case provide simple examples showing how to achieve site response analysis including parameter identification and uncertainty quantification using SimCenter tools and the DesignSafe cyber infrastructure.



+



+<p align="center">



+<img src="img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>


⬇️ Suggested change

-<img src="img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>



+<img src="../img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>



________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842042904>:

>



 ## Background







 ### Citation and Licensing







-* Please cite [AUTHORS et al. (20xx) - example of published project](https://doi.org/10.17603/ds2-3zdj-493) to acknowledge the use of any resources from this use case.



+* Please cite [Arduino, P. et al. (2022)](https://doi.org/10.17603/ds2-3zdj-493) to acknowledge the use of any resources from this use case.







 * Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.







 * This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).







 ### Description


⬇️ Suggested change

-### Description



+## Description



________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842043701>:

> @@ -1,89 +1,279 @@



-# TITLE for Use Case Documentation Page



+# From constitutive parameter calibration to site response analysis







 **Authors, Affiliations**


⬇️ Suggested change

-**Authors, Affiliations**



________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842043201>:

>



 * Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.







 * This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).







 ### Description







-Enim ut sem viverra aliquet.  Nisi scelerisque eu ultrices vitae auctor. Scelerisque viverra mauris in aliquam.  Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Sed adipiscing diam donec adipiscing tristique.  In pellentesque massa placerat duis. Tortor condimentum lacinia quis vel eros donec ac. Sed velit dignissim sodales ut eu sem. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Quis risus sed vulputate odio ut.



+Site response analysis for liquefiable soils is fundamental in the estimation of demands on civil infrastructure including buildings and lifelines. Current state of the art in numerical methods in geotechnical engineering require the use of advance constitutive models and fully couple nonlinear finite element (FEM) tools. Advanced constitutive models require calibration of material parameters based on experimental tests. These parameters include uncertainties that in turn propagate to uncertenties in the estimation of demands. The products included in this use-case provide simple examples showing how to achieve site response analysis including parameter identification and uncertainty quantification using SimCenter tools and the DesignSafe cyber infrastructure.



+



+<p align="center">



+<img src="img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>



Image url is one level up

________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842043086>:

>



 ## Background







 ### Citation and Licensing







-* Please cite [AUTHORS et al. (20xx) - example of published project](https://doi.org/10.17603/ds2-3zdj-493) to acknowledge the use of any resources from this use case.



+* Please cite [Arduino, P. et al. (2022)](https://doi.org/10.17603/ds2-3zdj-493) to acknowledge the use of any resources from this use case.







 * Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.







 * This software is distributed under the GNU General Public License (https://www.gnu [...]

2022-04-16 20:29 UTC, parduino commented
Hi Krishna,

  I made some additional changes based on your comments. It really help me see your page to undestand what you want.
One of the problems seems to be related to how headings will show in the master page… (now I see this problem).
For this purpose I changed my usecase.md page in such a way 4 headings show at the H2 level:

a)       Background

b)      Site response notebook (completed for this version)

c)       Parameter Calibration Notebook (in preparation)

d)      Propagation of uncertainty notebook (in preparation)

For the images the problem of relative is respect to what. I believe your ../img is because you are starting from the main page. Is this correct?
Can make any change you consider appropriate.

Pedro

From: Pedro Arduino
Sent: Saturday, April 16, 2022 12:21 PM
To: DesignSafe-CI/DS_Use_Case_template ***@***.***>; Krishna Kumar ***@***.***>
Subject: RE: [DesignSafe-CI/DS_Use_Case_template] Merging arduino use-case version1 (PR #18)

Hi Krishna,

  Silly question on use case document.
Why do you suggest to use


<img src="../img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>


If the img/ folder is in the same location as the usecase.md file… ??
Or are you planning to have a different location for the img folders??
I would use

<img src="img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>

I may be missing something here.. ☺

Pedro

From: Krishna Kumar ***@***.******@***.***>>
Sent: Monday, April 4, 2022 11:51 AM
To: DesignSafe-CI/DS_Use_Case_template ***@***.******@***.***>>
Cc: Pedro Arduino ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: Re: [DesignSafe-CI/DS_Use_Case_template] Merging arduino use-case version1 (PR #18)


@kks32 requested changes on this pull request.

Could you please update the doc with the suggested changes. Thanks
!

________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842040552>:

>



 ## Background







 ### Citation and Licensing







-* Please cite [AUTHORS et al. (20xx) - example of published project](https://doi.org/10.17603/ds2-3zdj-493) to acknowledge the use of any resources from this use case.



+* Please cite [Arduino, P. et al. (2022)](https://doi.org/10.17603/ds2-3zdj-493) to acknowledge the use of any resources from this use case.







 * Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.







 * This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).


⬇️ Suggested change

-* This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).



+* This software is distributed under the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.html).



________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842042641>:

>



 * Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.







 * This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).







 ### Description







-Enim ut sem viverra aliquet.  Nisi scelerisque eu ultrices vitae auctor. Scelerisque viverra mauris in aliquam.  Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Sed adipiscing diam donec adipiscing tristique.  In pellentesque massa placerat duis. Tortor condimentum lacinia quis vel eros donec ac. Sed velit dignissim sodales ut eu sem. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Quis risus sed vulputate odio ut.



+Site response analysis for liquefiable soils is fundamental in the estimation of demands on civil infrastructure including buildings and lifelines. Current state of the art in numerical methods in geotechnical engineering require the use of advance constitutive models and fully couple nonlinear finite element (FEM) tools. Advanced constitutive models require calibration of material parameters based on experimental tests. These parameters include uncertainties that in turn propagate to uncertenties in the estimation of demands. The products included in this use-case provide simple examples showing how to achieve site response analysis including parameter identification and uncertainty quantification using SimCenter tools and the DesignSafe cyber infrastructure.



+



+<p align="center">



+<img src="img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>


⬇️ Suggested change

-<img src="img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>



+<img src="../img/SRschematic2.PNG" alt="Propagation of vertical waves in site response analysis" width="600"/>



________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842042904>:

>



 ## Background







 ### Citation and Licensing







-* Please cite [AUTHORS et al. (20xx) - example of published project](https://doi.org/10.17603/ds2-3zdj-493) to acknowledge the use of any resources from this use case.



+* Please cite [Arduino, P. et al. (2022)](https://doi.org/10.17603/ds2-3zdj-493) to acknowledge the use of any resources from this use case.







 * Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.







 * This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).







 ### Description


⬇️ Suggested change

-### Description



+## Description



________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842043701>:

> @@ -1,89 +1,279 @@



-# TITLE for Use Case Documentation Page



+# From constitutive parameter calibration to site response analysis







 **Authors, Affiliations**


⬇️ Suggested change

-**Authors, Affiliations**



________________________________

In docs/arduino/usecase.md<https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/18#discussion_r842043201>:

>



 * Please cite [Rathje et al. (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) to acknowledge the use of DesignSafe resources.







 * This software is distributed under the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.html).







 ### Description







-Enim ut sem viverra aliquet.  Nisi scelerisque eu ultrices vitae auctor. Scelerisque viverra mauris in aliquam.  Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Sed adipiscing diam donec adipiscing tristique.  In pellentesque massa placerat duis. Tortor condimentum lacinia quis vel eros donec ac. Sed velit dignissim sodales ut eu sem. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Quis risus sed vulputate odio ut.



+Site response analysis for liquefiable soils is fundamental in the estimation of demands on civil infrastructure including buildings and lifelines. Current state of the art in numerical methods in geotechnical engineering require the use of advance constitutive models and fully couple nonlinear finite element (FEM) tools. Advanced constitutive models require calibration of material parameters based on experimental tests. These parameters include uncertainties that in turn propagate to uncertenties in the estimation of demands. The products included in this use-case provide simple examples showing how to achieve site response analysis including parameter identification and u [...]

2022-04-19 13:24 UTC, parduino commented
Hi Pedro,

Sorry for my slow reply, had lots of classes yesterday.

I'm working through the changes. Thanks for changing the headings, they 
look good now.

For the images, because you use direct html, the webpage for your 
usecase is 
https://deploy-preview-18--ds-use-case-preview.netlify.app/arduino/usecase/ 
and the image is actually located in `/arduino/img` so from the current 
`/arduino/usecase/` we have to go to the parent directory `/ardunio/` 
using `../img` to access the image folder.

I have edit access to your repo, so I can make these changes. Just 
explaining here for why we need to make this change. You don't have to 
do anything at the moment.

Thank you!!

- Krishna

On 4/16/22 3:28 PM, Pedro Arduino wrote:
>
> Hi Krishna,
>
> I made some additional changes based on your comments. It really help 
> me see your page to undestand what you want.
>
> One of the problems seems to be related to how headings will show in 
> the master page… (now I see this problem).
>
> For this purpose I changed my usecase.md page in such a way 4 headings 
> show at the H2 level:
>
> a)Background
>
> b)Site response notebook (completed for this version)
>
> c)Parameter Calibration Notebook (in preparation)
>
> d)Propagation of uncertainty notebook (in preparation)
>
> For the images the problem of relative is respect to what. I believe 
> your ../img is because you are starting from the main page. Is this 
> correct?
>
> Can make any change you consider appropriate.
>
> Pedro
>
> *From:*Pedro Arduino
> *Sent:* Saturday, April 16, 2022 12:21 PM
> *To:* DesignSafe-CI/DS_Use_Case_template 
> ***@***.***>; 
> Krishna Kumar ***@***.***>
> *Subject:* RE: [DesignSafe-CI/DS_Use_Case_template] Merging arduino 
> use-case version1 (PR #18)
>
> Hi Krishna,
>
> Silly question on use case document.
>
> Why do you suggest to use
>
> <img src="../img/SRschematic2.PNG" alt="Propagation of vertical waves 
> in site response analysis" width="600"/>
>
> If the img/ folder is in the same location as the usecase.md file… ??
>
> Or are you planning to have a different location for the img folders??
>
> I would use
>
> <img src="img/SRschematic2.PNG" alt="Propagation of vertical waves in 
> site response analysis" width="600"/>
>
> I may be missing something here.. J
>
> Pedro
>
> *From:*Krishna Kumar ***@***.***>
> *Sent:* Monday, April 4, 2022 11:51 AM
> *To:* DesignSafe-CI/DS_Use_Case_template 
> ***@***.***>
> *Cc:* Pedro Arduino ***@***.***>; Author ***@***.***>
> *Subject:* Re: [DesignSafe-CI/DS_Use_Case_template] Merging arduino 
> use-case version1 (PR #18)
>
> ***@***.**** requested changes on this pull request.
>
> Could you please update the doc with the suggested changes. Thanks
> !
>
> ------------------------------------------------------------------------
>
> In docs/arduino/usecase.md 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDesignSafe-CI%2FDS_Use_Case_template%2Fpull%2F18%23discussion_r842040552&data=04%7C01%7C%7C646e6f5858ba4150798108da1fe7c400%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637857377570977360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2yapboYYGDIr3zITPvbQQh2qurEXdjRvXK10XmHX3P0%3D&reserved=0>:
>
> >  
> ## Background
> ### Citation and Licensing
> -* Please cite [AUTHORS et al. (20xx) - example of published 
> project](https://doi.org/10.17603/ds2-3zdj-493 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.17603%2Fds2-3zdj-493&data=04%7C01%7C%7C646e6f5858ba4150798108da1fe7c400%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637857377570977360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=joMxBQv32Iczn71qJK2oFETRyzOI%2FwF1vNzY2Rcu%2BxM%3D&reserved=0>) 
> to acknowledge the use of any resources from this use case.
> +* Please cite [Arduino, P. et al. 
> (2022)](https://doi.org/10.17603/ds2-3zdj-493 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.17603%2Fds2-3zdj-493&data=04%7C01%7C%7C646e6f5858ba4150798108da1fe7c400%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637857377570977360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=joMxBQv32Iczn71qJK2oFETRyzOI%2FwF1vNzY2Rcu%2BxM%3D&reserved=0>) 
> to acknowledge the use of any resources from this use case.
> * Please cite [Rathje et al. 
> (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1061%2F(ASCE)NH.1527-6996.0000246)&data=04%7C01%7C%7C646e6f5858ba4150798108da1fe7c400%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637857377570977360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AqKeTC228ErDkRVFcnDu40hx4I7xlwvh03oHB0%2BoaqM%3D&reserved=0> 
> to acknowledge the use of DesignSafe resources.
> * This software is distributed under the GNU General Public License 
> (https://www.gnu.org/licenses/gpl-3.0.html 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gnu.org%2Flicenses%2Fgpl-3.0.html&data=04%7C01%7C%7C646e6f5858ba4150798108da1fe7c400%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637857377570977360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=U%2BkYU%2Fth9MAcXvgr7l5%2FfIPRiDDmDljIG4N3aaQ0UjE%3D&reserved=0>). 
>
>
> ⬇️ Suggested change
>
> -* This software is distributed under the GNU General Public License 
> (https://www.gnu.org/licenses/gpl-3.0.html 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gnu.org%2Flicenses%2Fgpl-3.0.html&data=04%7C01%7C%7C646e6f5858ba4150798108da1fe7c400%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637857377570977360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=U%2BkYU%2Fth9MAcXvgr7l5%2FfIPRiDDmDljIG4N3aaQ0UjE%3D&reserved=0>). 
>
> +* This software is distributed under the [GNU General Public 
> License](https://www.gnu.org/licenses/gpl-3.0.html 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gnu.org%2Flicenses%2Fgpl-3.0.html&data=04%7C01%7C%7C646e6f5858ba4150798108da1fe7c400%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637857377571133614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LsBRwJ%2FMVfh1pIkR%2Fa7qUCkjXSXjAFkNBJiizH5IilI%3D&reserved=0>). 
>
> ------------------------------------------------------------------------
>
> In docs/arduino/usecase.md 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDesignSafe-CI%2FDS_Use_Case_template%2Fpull%2F18%23discussion_r842042641&data=04%7C01%7C%7C646e6f5858ba4150798108da1fe7c400%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637857377571133614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=42VfIBXYYyR%2FZWgHWhJXcWXztOhqxitkeYSnu5jVYZQ%3D&reserved=0>:
>
> >  
> * Please cite [Rathje et al. 
> (2017)](https://doi.org/10.1061/(ASCE)NH.1527-6996.0000246) 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1061%2F(ASCE)NH.1527-6996.0000246)&data=04%7C01%7C%7C646e6f5858ba4150798108da1fe7c400%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637857377571133614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mL75mlYByjapVisR7hcZLScYoqshYhk3u9uhcI8LDUA%3D&reserved=0> 
> to acknowledge the use of DesignSafe resources.
> * This software is distributed under the GNU General Public License 
> (https://www.gnu.org/licenses/gpl-3.0.html 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gnu.org%2Flicenses%2Fgpl-3.0.html&data=04%7C01%7C%7C646e6f5858ba4150798108da1fe7c400%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637857377571133614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIj [...]

2022-04-19 13:50 UTC, kks32 approved these changes

2022-04-19 13:50 UTC, merged