Updates to ML Use Case
DesignSafe-CI/DS_Use_Case_template pull request #20
Opened 2022-04-01 23:46 UTC by jpvantassel

# In this PR

- ✨ Description and overview
- ✨ Add links to ml notebooks in community data.
- 🔥 Remove unused image file.

2022-04-04 19:18 UTC, kks32 commented on docs/vantassel_and_zhang/usecase.md
> +## Citation and Licensing
This needs to be at the top

2022-04-04 19:19 UTC, kks32 requested changes
Rearrange to move citations to the top of the page

2022-04-04 19:33 UTC, jpvantassel commented on docs/vantassel_and_zhang/usecase.md
> +## Citation and Licensing
Done

2022-04-19 12:59 UTC, kks32 commented on docs/vantassel_and_zhang/usecase.md
> +* This software is distributed under the GNU General Public License ([https://www.gnu.org/licenses/gpl-3.0.html](https://www.gnu.org/licenses/gpl-3.0.html)).
```suggestion
* This software is distributed under the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.html).
```

2022-04-19 12:59 UTC, kks32 requested changes
Can you give me edit access?

- Fix mkdocs.yml file folder `ml_resources`
- GPL license link change

2022-04-19 16:24 UTC, kks32 approved these changes

2022-04-19 16:25 UTC, merged