Updating usecase
DesignSafe-CI/DS_Use_Case_template pull request #37
Opened 2023-05-07 17:57 UTC by stokljos

changed a section and updated some files.

2023-05-08 02:28 UTC, kks32 requested changes
I'd request to move the description of different functions from the usecase file to ipynb files in DesignSafe. Could you please add descriptions and comments to the ipynb files?

The usecase can give a high-level overview of the different sections.

2023-05-08 02:28 UTC, kks32 commented on docs/lowes/usecase.md
> +(Script needs to be established on design safe. I have a working notebook, just need to connect it with modeling script)
I'll wait until you complete this...

2023-05-08 02:40 UTC, stokljos commented
Hello,

I have updated notebooks I am trying to add to design safe but I am unable
to. What's the best way to do this for the use case jupyter files? All
those files have descriptions.

And then following what you are saying, I shouldn't a quick summary of the
outputs for each notebook? I thought that would give the user a good
overview of how the notebook works and what is expected for the output?

I am also no longer a student and have a pretty full schedule at work. I
have not been to a designsafe meeting in almost a year as well so i am not
update to date. I was contacted by my professor just to update the
notebooks, I have very limited time before the 15th as I am in the middle
of moving and on vacation this next week.


On Sun, May 7, 2023, 7:28 PM Krishna Kumar ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I'd request to move the description of different functions from the
> usecase file to ipynb files in DesignSafe. Could you please add
> descriptions and comments to the ipynb files?
>
> The usecase can give a high-level overview of the different sections.
> ------------------------------
>
> In docs/lowes/usecase.md
> <https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/37#discussion_r1186966060>
> :
>
> >
> -### Code
> +(Script needs to be established on design safe. I have a working notebook, just need to connect it with modeling script)
>
> I'll wait until you complete this...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/37#pullrequestreview-1416032346>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOGTV27RCBTPTFKZU7VIUTLXFBK5NANCNFSM6AAAAAAXZA47OY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-17 01:09 UTC, kks32 commented
@stokljos I have merge conflicts. Could you please resolve those?

2023-05-17 01:35 UTC, kks32 approved these changes

2023-05-17 01:35 UTC, merged